version: '3'

services:
   httpd:
     container_name: ${CONTAINER_NAME}
     image: httpd:alpine
     restart: unless-stopped
     volumes:
       - ${HTTPD_CONTENT}:/var/www/html
     environment:
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}